### ISSUE TITLE
无法运行！！！！！！！

### ISSUE THREAD

**Issue by lieying8** [Sunnyyoung/WeChatTweak-macOS#373]
![1](https://user-images.githubusercontent.com/60979836/140065733-66d76c12-542a-4573-b1d7-44fc241bf41e.png)

**Comment by Sunnyyoung** [comment]
先安装 `brew install sunnyyoung/repo/swift-runtime-support` ！！！！！！

**Comment by zz412000428** [comment]
执行 `brew install sunnyyoung/repo/swift-runtime-support`
执行版本：macOS Monterey 12.0.1(21A559)

installer: Cannot install on volume / because it is disabled.
installer: macOS的版本太高。

**Comment by Sunnyyoung** [comment]
啊？你的 Monterey 为什么报错缺 libswiftCore 😂，装一下 `xcode-select --install` 试试

**Comment by zz412000428** [comment]
这个已经执行过了，`xcode-select --install`
我就是在转完xcode之后执行的`brew install`

**Comment by Sunnyyoung** [comment]
@zz412000428 无法复现

**Comment by lieying8** [comment]
> 先安装`brew install sunnyyoung/repo/swift-runtime-support`！！！！
<img width="617" alt="11" src="https://user-images.githubusercontent.com/60979836/140374684-0269c254-a426-4987-999d-5edafce5f9bb.png">
安装过了，又出现这种情况

**Comment by leecss** [comment]
我和上面的兄弟一样的问题，安装swift-runtime-support提示macOS的版本太高。
执行版本：macOS Monterey 12.0.1
`❯ brew install sunnyyoung/repo/swift-runtime-support
==> Downloading https://updates.cdn-apple.com/2019/cert/061-41823-20191025-5efc5a59-d7dc-46d3-9096-396bb8cb4a73/SwiftRuntimeForCommandLineTools.dmg
######################################################################## 100.0%
==> Installing Cask swift-runtime-support
==> Running installer for swift-runtime-support; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
Password:
installer: Cannot install on volume / because it is disabled.
installer: macOS的版本太高。
==> Purging files for version 061-41823-20191025-5efc5a59-d7dc-46d3-9096-396bb8cb4a73 of Cask swift-runtime-support
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=licong USER=licong USERNAME=licong /usr/sbin/installer -pkg /opt/homebrew/Caskroom/swift-runtime-support/061-41823-20191025-5efc5a59-d7dc-46d3-9096-396bb8cb4a73/SwiftRuntimeForCommandLineTools.pkg -target /` exited with 1. Here's the output:
installer: Cannot install on volume / because it is disabled.
installer: macOS的版本太高。
❯ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates`

**Comment by lieying8** [comment]
> @zz412000428 啊？你的 Monterey 为什么报错缺 libswiftCore 😂，装一下 `xcode-select --install` 试试

之前的微信版本可以用，升级到3.7以后就没法用了，重新安装你的1.22就出现报错，至今无法使用   10.12系统

**Comment by Sunnyyoung** [comment]
1. 卸载再安装
2. 重启电脑

基本都可以解决了
